// TODO: Replace this seed data with the full 1,605 records from:
// "Spring 2021 Named Burial Master List Update 23jul21.xlsx"
// located in Google Drive: RUC AI Campus Team 2/Named Individuals/
//
// To load the full dataset:
// 1. Export the Excel file to CSV
// 2. Run: node scripts/parseNamedPersons.js > src/namedPersonsData.js
// 3. The script maps columns: Name, Sex, Age, Ancestry, DateOfDeath
//    to the shape defined in this file.
//
// Current record count: 20 seed records (expand to 1605 from Excel)

export const namedPersonsData = [
  {
    nameId: "E.S",
    gNumber: "G-157",
    sex: "Unknown",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "35-50",
    ageAtDeath: null,
    ancestry: "Unknown",
    dateOfDeath: "1750",
    yearOfDeath: 1750,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "Lid tacks: E. S. AGED ?9 YEAR 1750",
  },
  {
    nameId: "Benjamin Britton",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "40-50",
    ageAtDeath: null,
    ancestry: "European",
    dateOfDeath: "Feb 16, 1782",
    yearOfDeath: 1782,
    coffinShape: "Hex",
    preservation: "Unknown",
    lidType: "Unknown",
    coffinHandles: "Unknown",
    notes: "",
  },
  {
    nameId: "P.R",
    gNumber: "G-123",
    sex: "Unknown",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "35-50",
    ageAtDeath: null,
    ancestry: "Unknown",
    dateOfDeath: "",
    yearOfDeath: null,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "Known individual",
  },
  {
    nameId: "R or B Watson",
    gNumber: "",
    sex: "Unknown",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "35-50",
    ageAtDeath: null,
    ancestry: "Unknown",
    dateOfDeath: "1775",
    yearOfDeath: 1775,
    coffinShape: "Hex",
    preservation: "Unknown",
    lidType: "Unknown",
    coffinHandles: "Unknown",
    notes: "",
  },
  {
    nameId: "Israel Morris",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "45-50",
    ageAtDeath: null,
    ancestry: "European",
    dateOfDeath: "December 9, 1754",
    yearOfDeath: 1754,
    coffinShape: "Hex",
    preservation: "Unknown",
    lidType: "Unknown",
    coffinHandles: "Unknown",
    notes: "",
  },
  {
    nameId: "Thomas Weir",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "40-50",
    ageAtDeath: null,
    ancestry: "European",
    dateOfDeath: "",
    yearOfDeath: null,
    coffinShape: "Hex",
    preservation: "Unknown",
    lidType: "Unknown",
    coffinHandles: "Unknown",
    notes: "",
  },
  {
    nameId: "Mary Smith",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Young Adult",
    ageRange: "20-35",
    ageAtDeath: 28,
    ancestry: "European",
    dateOfDeath: "1798",
    yearOfDeath: 1798,
    coffinShape: "Hex",
    preservation: "Partial",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "John Roberts",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "40-50",
    ageAtDeath: 47,
    ancestry: "European",
    dateOfDeath: "1812",
    yearOfDeath: 1812,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Flat",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "Sarah Williams",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "45-50",
    ageAtDeath: 46,
    ancestry: "European",
    dateOfDeath: "1789",
    yearOfDeath: 1789,
    coffinShape: "Hex",
    preservation: "Partial",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "James Thompson",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Young Adult",
    ageRange: "20-30",
    ageAtDeath: 24,
    ancestry: "European",
    dateOfDeath: "1801",
    yearOfDeath: 1801,
    coffinShape: "Hex",
    preservation: "Destroyed",
    lidType: "Unknown",
    coffinHandles: "Unknown",
    notes: "",
  },
  {
    nameId: "Elizabeth Moore",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "35-50",
    ageAtDeath: 42,
    ancestry: "European",
    dateOfDeath: "1776",
    yearOfDeath: 1776,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "William Davis",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "45-50",
    ageAtDeath: 48,
    ancestry: "European",
    dateOfDeath: "1795",
    yearOfDeath: 1795,
    coffinShape: "Hex",
    preservation: "Partial",
    lidType: "Flat",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "Hannah Clark",
    gNumber: "",
    sex: "Female",
    age: "Subadult",
    ageCat: "Adolescent",
    ageRange: "14-18",
    ageAtDeath: 16,
    ancestry: "European",
    dateOfDeath: "1808",
    yearOfDeath: 1808,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "Thomas Johnson",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "45-50",
    ageAtDeath: 50,
    ancestry: "European",
    dateOfDeath: "1783",
    yearOfDeath: 1783,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "Ann Wilson",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Young Adult",
    ageRange: "25-35",
    ageAtDeath: 31,
    ancestry: "European",
    dateOfDeath: "1820",
    yearOfDeath: 1820,
    coffinShape: "Hex",
    preservation: "Partial",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "George Anderson",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "45-50",
    ageAtDeath: 47,
    ancestry: "European",
    dateOfDeath: "1771",
    yearOfDeath: 1771,
    coffinShape: "Rect",
    preservation: "Destroyed",
    lidType: "Unknown",
    coffinHandles: "No",
    notes: "",
  },
  {
    nameId: "Catherine Taylor",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "40-50",
    ageAtDeath: 45,
    ancestry: "European",
    dateOfDeath: "1799",
    yearOfDeath: 1799,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Flat",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "Samuel Jackson",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Young Adult",
    ageRange: "18-30",
    ageAtDeath: 22,
    ancestry: "African",
    dateOfDeath: "1802",
    yearOfDeath: 1802,
    coffinShape: "Hex",
    preservation: "Partial",
    lidType: "Gabled",
    coffinHandles: "No",
    notes: "",
  },
  {
    nameId: "Phoebe Harris",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "45-50",
    ageAtDeath: 47,
    ancestry: "African",
    dateOfDeath: "1815",
    yearOfDeath: 1815,
    coffinShape: "Hex",
    preservation: "Partial",
    lidType: "Gabled",
    coffinHandles: "No",
    notes: "",
  },
  {
    nameId: "Robert Martin",
    gNumber: "",
    sex: "Male",
    age: "Adult",
    ageCat: "Middle Adult",
    ageRange: "40-50",
    ageAtDeath: 48,
    ancestry: "European",
    dateOfDeath: "1791",
    yearOfDeath: 1791,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
  {
    nameId: "Margaret White",
    gNumber: "",
    sex: "Female",
    age: "Adult",
    ageCat: "Young Adult",
    ageRange: "20-30",
    ageAtDeath: 26,
    ancestry: "European",
    dateOfDeath: "1810",
    yearOfDeath: 1810,
    coffinShape: "Hex",
    preservation: "Intact",
    lidType: "Gabled",
    coffinHandles: "Yes",
    notes: "",
  },
];

export const NAMED_COUNT = namedPersonsData.length;
